# Generated by Django 4.2.30 on 2026-08-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='programkerja',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Tampilkan di Highlighted Programs di halaman Home.'),
        ),
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About SISO'), ('program', 'Program Kerja & Events'), ('articles', 'Articles'), ('contact', 'Contact')], max_length=30),
        ),
    ]
