# Generated by Django 4.2.30 on 2026-08-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_featured_caption_articles_page'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_visible', 'category'], name='article_visible_category_idx'),
        ),
        migrations.AddIndex(
            model_name='programkerja',
            index=models.Index(fields=['is_visible', 'category'], name='program_visible_category_idx'),
        ),
        migrations.AddIndex(
            model_name='programkerja',
            index=models.Index(fields=['is_visible', 'is_featured'], name='program_visible_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='programkerja',
            index=models.Index(fields=['is_visible', 'date'], name='program_visible_date_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['page', 'is_visible'], name='section_page_visible_idx'),
        ),
    ]
