# Generated by Django 4.2.30 on 2026-09-27 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_article_article_visible_category_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
            ],
            options={
                'verbose_name': 'Section About',
                'verbose_name_plural': '2. Halaman About',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.section',),
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
            ],
            options={
                'verbose_name': 'Section Artikel',
                'verbose_name_plural': '4. Halaman Artikel & Prestasi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.section',),
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
            ],
            options={
                'verbose_name': 'Section Contact',
                'verbose_name_plural': '5. Halaman Contact & FAQ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.section',),
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
            ],
            options={
                'verbose_name': 'Section Home',
                'verbose_name_plural': '1. Halaman Home',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.section',),
        ),
        migrations.CreateModel(
            name='ProgramSection',
            fields=[
            ],
            options={
                'verbose_name': 'Section Program',
                'verbose_name_plural': '3. Halaman Program Kerja',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.section',),
        ),
    ]
