# Generated by Django 4.2.30 on 2026-09-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_aboutsection_articlesection_contactsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySection',
            fields=[
            ],
            options={
                'verbose_name': 'Section Gallery',
                'verbose_name_plural': '5. Halaman Gallery',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.section',),
        ),
        migrations.AlterModelOptions(
            name='contactsection',
            options={'verbose_name': 'Section Contact', 'verbose_name_plural': '6. Halaman Contact & FAQ'},
        ),
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About SISO'), ('program', 'Program Kerja & Events'), ('articles', 'Articles'), ('gallery', 'Gallery & Dokumentasi'), ('contact', 'Contact')], max_length=30),
        ),
    ]
