# Generated by Django 4.2.30 on 2026-09-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_gallerysection_alter_contactsection_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSection',
        ),
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About SISO'), ('program', 'Program Kerja & Events'), ('articles', 'Articles'), ('gallery', 'Gallery & Dokumentasi')], max_length=30),
        ),
    ]
