# Generated by Django 4.2.30 on 2026-09-27 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_delete_contactsection_alter_section_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='FormSubmission',
        ),
    ]
