# Generated by Django 4.2.30 on 2026-09-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_delete_contactinfo_delete_faq_delete_formsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesection',
            options={'verbose_name': 'Section Artikel & Prestasi', 'verbose_name_plural': '5. Halaman Artikel & Prestasi'},
        ),
        migrations.AlterModelOptions(
            name='gallerysection',
            options={'verbose_name': 'Section Gallery', 'verbose_name_plural': '4. Halaman Gallery'},
        ),
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About SISO'), ('program', 'Program Kerja & Events'), ('gallery', 'Gallery & Dokumentasi'), ('articles', 'Articles & Prestasi')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='bphmember',
            index=models.Index(fields=['generation_year'], name='content_bph_generat_0b51d3_idx'),
        ),
    ]
